### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by michaelcunning** [aniruddhanath/jquery-hotspot#10]
Hello, I am using v2.0.2 and the dots are not responsive on your examples or on my own. When I shrink down the browser, the spots move off the images. If you could advise, that would be wonderful thanks

**Comment by aniruddhanath** [comment]
Currently not listening to on-resize event. It should work when you refresh the browser.

**Comment by michaelcunning** [comment]
I see yes it does when I refresh. I though it might adjust as the browser
size was adjusted.thanks for clarifying
