### ISSUE TITLE
how to print data sent by ajax

### ISSUE THREAD

**Issue by irandoct** [aniruddhanath/jquery-hotspot#15]
Hi,
I want to save posted data to mysql database. I activate ajax method. My code:
$(document).ready(function(){
	var TreatmentID = $("#theElement-a").attr("TreatmentID");
	$("#theElement-a").hotspot({
	mode: "admin",
    schema: [
    {
      'property': 'TreatmentID',
      'default': TreatmentID
    },
    {
      'property': 'Date',
      'default': '12/11/2018'
    },
    ],
			// uncomment
			ajax: true,
			ajaxOptions: {
				'url': 'saveguide.php'
			},
			interactivity: "click",
			LS_Variable: "HotspotPlugin-a",

			afterSave: function(err, data) {
				if (err) {
					console.log('Error occurred', err);
					return;
				}
				alert('success');
				// `data` in json format can be stored
				//  & passed in `display` mode for the image
				console.log(data);
			},
			afterRemove: function(err, message) {
				if (err) {
					console.log('Error occurred', err);
					return;
				}
				alert(message);
				window.location.reload();
			},
			afterSend: function(err, message) {
				if (err) {
					console.log('Error occurred', err);
					return;
				}
				alert(message);
			}
		});
});

how to print posted values in saveguide.php file?

Thank you
Mansour

**Comment by aniruddhanath** [comment]
In php, you can read the data from `$_GET['HotspotPlugin_data']`. When using `type: 'POST'` in `ajaxOptions` the same is available at `$_POST['HotspotPlugin_data']`
