### ISSUE TITLE
Hotspots on wordpress website 

### ISSUE THREAD

**Issue by marineb30** [aniruddhanath/jquery-hotspot#3]
Hello, 
First of all, thanks for this very nice plugin.
I work under wordpress and have tried to use the jquery-hotspot, but I have some problems.
If I write the following html in the php file of my page:

`	<div class="panel panel-info" id="example-admin">
		<div class="panel-heading">
			<h4>Example - Admin mode</h4>
		</div>
		<div class="panel-body">

			    <div class="col-md-6">

				<div id="theElement">
					<img src="IMG_5990.JPG" width="480" height="400">
				</div>
				</div>
		</div>
	</div>`

and the css needed:

`#theElement {
    position: relative;
    display: inline-block;
}`

and the following javascript in my js file:

`(function($) {
$(document).ready(function() {

$('#theElement').hotspot({
    data: [
        { "x":288, "y":390, "Title":"The Title","Message":"Create the Message here" },
        { "x":143, "y":400, "Title":"jQuery Hotspot","Message":"This jQuery Plugin lets you create hotspot to any HTML element." }
    ],
    tag: 'img', //optional (default is img)
    interactivity: "hover", // options : click, none (default is hover)
    hotspotClass: 'Hotspot'
});
        }); 
})(jQuery);`

My image is displayed but I have this error :
![pb1](https://cloud.githubusercontent.com/assets/25684238/22822619/72df5438-ef80-11e6-9fd8-f5f38ed906f4.png)

I tried to add { braces just after the ( brackets but it still doesn't work, and hotspots never appear.. :
![pb2](https://cloud.githubusercontent.com/assets/25684238/22822746/f43451e6-ef80-11e6-8aad-c6bfd0f2ed61.png)

Hoping you can help me,
Thanks a lot,
Marine

**Comment by aniruddhanath** [comment]
The screenshot has an invalid javascript object. Also, hotspots will not appear if the css properties are not correctly set.
