### ISSUE TITLE
Problem In Responsive View.

### ISSUE THREAD

**Issue by sathishcst10** [aniruddhanath/jquery-hotspot#4]
Hi,
I need this Hotspot creator in responsive view, how to get X,Y Positions in Percentage ?
i want to host this in mobile based app.
please help me.

**Comment by bdthemes** [comment]
Same issue for me too! how to responsive it?

**Comment by aniruddhanath** [comment]
Existing code doesn't ensure responsiveness. You'll need to change the source code of the plugin in order to do that.

**Comment by bdthemes** [comment]
Hello @aniruddhanath,  your plugin very good just need to add a responsive feature. why not keep update it?

**Comment by aniruddhanath** [comment]
Release new version v2.0.1 which supports responsiveness. Please check it out.

**Comment by GoodPixe1** [comment]
Sorry to resurrect an old issue but I really need the hotspots to reposition on browser resize, is there any easy way to accomplish this?

**Comment by aniruddhanath** [comment]
@GoodPixe1 current it is not possible. But I'm planning to add a hook there to clear the hotspots.
This can be used along with current available method on browser's onresize events.
